namespace Novacode
{
	public static class XmlTemplateBases
	{
		public const string TocXmlBase = "<w:sdt xmlns:w='http://schemas.openxmlformats.org/wordprocessingml/2006/main'>\r\n                  <w:sdtPr>\r\n                    <w:docPartObj>\r\n                      <w:docPartGallery w:val='Table of Contents'/>\r\n                      <w:docPartUnique/>\r\n                    </w:docPartObj>\\\r\n                  </w:sdtPr>\r\n                  <w:sdtEndPr>\r\n                    <w:rPr>\r\n                      <w:rFonts w:asciiTheme='minorHAnsi' w:cstheme='minorBidi' w:eastAsiaTheme='minorHAnsi' w:hAnsiTheme='minorHAnsi'/>\r\n                      <w:color w:val='auto'/>\r\n                      <w:sz w:val='22'/>\r\n                      <w:szCs w:val='22'/>\r\n                      <w:lang w:eastAsia='en-US'/>\r\n                    </w:rPr>\r\n                  </w:sdtEndPr>\r\n                  <w:sdtContent>\r\n                    <w:p>\r\n                      <w:pPr>\r\n                        <w:pStyle w:val='{0}'/>\r\n                      </w:pPr>\r\n                      <w:r>\r\n                        <w:t>{1}</w:t>\r\n                      </w:r>\r\n                    </w:p>\r\n                    <w:p>\r\n                      <w:pPr>\r\n                        <w:pStyle w:val='TOC1'/>\r\n                        <w:tabs>\r\n                          <w:tab w:val='right' w:leader='dot' w:pos='{2}'/>\r\n                        </w:tabs>\r\n                        <w:rPr>\r\n                          <w:noProof/>\r\n                        </w:rPr>\r\n                      </w:pPr>\r\n                      <w:r>\r\n                        <w:fldChar w:fldCharType='begin' w:dirty='true'/>\r\n                      </w:r>\r\n                      <w:r>\r\n                        <w:instrText xml:space='preserve'> {3} </w:instrText>\r\n                      </w:r>\r\n                      <w:r>\r\n                        <w:fldChar w:fldCharType='separate'/>\r\n                      </w:r>\r\n                    </w:p>\r\n                    <w:p>\r\n                      <w:r>\r\n                        <w:rPr>\r\n                          <w:b/>\r\n                          <w:bCs/>\r\n                          <w:noProof/>\r\n                        </w:rPr>\r\n                        <w:fldChar w:fldCharType='end'/>\r\n                      </w:r>\r\n                    </w:p>\r\n                  </w:sdtContent>\r\n                </w:sdt>\r\n            ";

		public const string TocHeadingStyleBase = "<w:style w:type='paragraph' w:styleId='{0}' xmlns:w='http://schemas.openxmlformats.org/wordprocessingml/2006/main'>\r\n            <w:name w:val='TOC Heading'/>\r\n            <w:basedOn w:val='Heading1'/>\r\n            <w:next w:val='Normal'/>\r\n            <w:uiPriority w:val='39'/>\r\n            <w:semiHidden/>\r\n            <w:unhideWhenUsed/>\r\n            <w:qFormat/>\r\n            <w:rsid w:val='00E67AA6'/>\r\n            <w:pPr>\r\n              <w:outlineLvl w:val='9'/>\r\n            </w:pPr>\r\n            <w:rPr>\r\n              <w:lang w:eastAsia='nb-NO'/>\r\n            </w:rPr>\r\n          </w:style>\r\n        ";

		public const string TocElementStyleBase = "  <w:style w:type='paragraph' w:styleId='{0}' xmlns:w='http://schemas.openxmlformats.org/wordprocessingml/2006/main'>\r\n            <w:name w:val='{1}' />\r\n            <w:basedOn w:val='Normal' />\r\n            <w:next w:val='Normal' />\r\n            <w:autoRedefine />\r\n            <w:uiPriority w:val='39' />\r\n            <w:unhideWhenUsed />\r\n            <w:pPr>\r\n              <w:spacing w:after='100' />\r\n              <w:ind w:left='440' />\r\n            </w:pPr>\r\n          </w:style>\r\n        ";

		public const string TocHyperLinkStyleBase = "  <w:style w:type='character' w:styleId='Hyperlink' xmlns:w='http://schemas.openxmlformats.org/wordprocessingml/2006/main'>\r\n            <w:name w:val='Hyperlink' />\r\n            <w:basedOn w:val='Normal' />\r\n            <w:uiPriority w:val='99' />\r\n            <w:unhideWhenUsed />\r\n            <w:rPr>\r\n              <w:color w:val='0000FF' w:themeColor='hyperlink' />\r\n              <w:u w:val='single' />\r\n            </w:rPr>\r\n          </w:style>\r\n        ";
	}
}
